### ISSUE TITLE
Allow to add a list of urls that bypass the gateway

### ISSUE THREAD

**Issue by qubird** [yunojuno/django-perimeter#10]
At the moment django-perimeter wraps _all urls_.
It would be useful allowing to specify a list of endpoints/regexes that bypass perimeter.

**Comment by hugorodgerbrown** [comment]
Originally I had a setting **BYPASS_PERIMETER_FUNCTION** that would be a lambda that would allow you to interrogate the `request` object so that you could bypass based on the user, the url, the request etc. This is my preferred option, rather than just URLs.

**Comment by stevejalim** [comment]
Handled, via BYPASS_PERIMITER_FUNCTION, introduced in https://github.com/yunojuno/django-perimeter/commit/2d3996c9bb098fc37a725bd71ab6c47b3fc3ece5
