### ISSUE TITLE
Feature request: carry querystrings through in the post-gateway redirect

### ISSUE THREAD

**Issue by stevejalim** [yunojuno/django-perimeter#12]
eg

`GET http://example.com/path/to/thing/?token=foobarbaz`

if that gets intercepted by Perimiter, the redirect url becomes

`/perimeter/gateway/?next=/path/to/thing` with no querystring on there.

I know that in practical terms it's not a big deal, but nice to sort out

**Comment by hugorodgerbrown** [comment]
Interesting - how do you get a '?' into a querystring as a value - if you url_encode, does it then get properly decoded when rendered on the final url?

**Comment by stevejalim** [comment]
I'd go with `urllib.quote_plus`:

```
In [6]: example
Out[6]: 'path/to/?my=thing'

In [7]: urllib.quote_plus(example)
Out[7]: 'path/to/%3Fmy%3Dthing'

In [8]: urllib.unquote(urllib.quote(example))
Out[8]: 'path/to/?my=thing'
```

In https://github.com/yunojuno/django-perimeter/blob/master/perimeter/middleware.py#L73

Changing
`'?next=%s' % request.path`
to
`'?next=%s' % urllib.quote_plus(request.get_full_path())`

(https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpRequest.get_full_path)

And in https://github.com/yunojuno/django-perimeter/blob/master/perimeter/views.py#L43

Changing
`request.GET.get('next'))`
to
`urllib.unquote(request.GET.get('next', '')))`
should do it.

**Comment by hugorodgerbrown** [comment]
Release as 0.6.7
