### ISSUE TITLE
Allow whitelisting 

### ISSUE THREAD

**Issue by stevejalim** [yunojuno/django-perimeter#18]
Sometimes, I need to leave a site behind perimeter, but then get messed up when a third-party needs to contact it (eg am developing a webhook integration).

It'd be handy if one could whitelist one/all of these:

- specific URL paths
- specific Django URL namespaces
- certain content types (eg, allow requests with an `Accepts` header of `application/json` and a view/resource which returns that same content type. This may be a nightmare to make secure, but would allow machine users to still poke a site that's behind a no-humans-yet-please perimeter)

**Comment by hugorodgerbrown** [comment]
Agreed. We could use a combination of a callable as a setting (e.g. allow access to the login page and is_staff users, but nothing more), together with db-backed editable rules for punching holes in it  ad hoc. Basically, what the request-profiler does? https://github.com/yunojuno/django-request-profiler/blob/master/request_profiler/settings.py

**Comment by hugorodgerbrown** [comment]
This is now covered by #21 - you can use an HTTP header to bypass the perimeter, which should allow automated tools to get through.
