### ISSUE TITLE
Remove print statement

### ISSUE THREAD

**Issue by nwjlyons** [yunojuno/django-perimeter#8]
I'm not sure it's necessary to print `PERIMETER_ENABLED` and `PERIMETER_DEFAULT_EXPIRY` immediately after running any Django management command when `DEBUG` is `True` https://github.com/yunojuno/django-perimeter/blob/master/perimeter/settings.py#L39

When running [dumpdata](https://docs.djangoproject.com/en/1.8/ref/django-admin/#dumpdata-app-label-app-label-app-label-model) and redirecting stdout + stderr to a file these two PERIMETER lines appear at the top of fixtures.

**Comment by hugorodgerbrown** [comment]
Feel free to fix !

Sent using Boxer

On 30 Jul 2015 13:05, Neil Lyons notifications@github.com wrote:

I'm not sure it's necessary to print PERIMETER_ENABLED and PERIMETER_DEFAULT_EXPIRY immediately after running any Django management command when DEBUG is True https://github.com/yunojuno/django-perimeter/blob/master/perimeter/settings.py#L39

When running dumpdata and redirecting stdout + stderr to a file these two PERIMETER lines appear at the top of fixtures.

**Comment by stevejalim** [comment]
Merged and version updated, etc but needs a new release to PyPi by @hugorodgerbrown as I don't have access to this proj on pypi

Just pull on `master` and `python setup.py sdist upload`

**Comment by hugorodgerbrown** [comment]
Pushed to pypi. @stevejalim you are a maintainer on this package now.
